<?define('A_PRODUCT_IMG_URL','http://'.$_SERVER['SERVER_NAME'].'/modules/catalog/images/product_img/');
define('A_PRODUCT_SMALL_IMG_W','50');
define('A_PRODUCT_SMALL_IMG_H','50');
define('A_PRODUCT_MID_IMG_W','170');
define('A_PRODUCT_MID_IMG_H','170');
define('A_MANUFACTURERS_IMG_SIZE','500000');
define('A_MANUFACTURERS_IMG_DIR',''.$_SERVER['DOCUMENT_ROOT'].'/modules/catalog/images/manufacturers_img/');
define('A_MANUFACTURERS_IMG_URL','http://'.$_SERVER['SERVER_NAME'].'/modules/catalog/images/manufacturers_img/');
define('A_MANUFACTURERS_SMALL_IMG_W','50');
define('A_MANUFACTURERS_SMALL_IMG_H','50');
define('A_MANUFACTURERS_MID_IMG_W','170');
define('A_MANUFACTURERS_MID_IMG_H','170');
define('CATALOG_SCRIPT_DIR',''.$_SERVER['DOCUMENT_ROOT'].'/modules/catalog/');
define('A_CATALOG_IMG_SIZE','5000000');
define('A_CATALOG_IMG_DIR',''.$_SERVER['DOCUMENT_ROOT'].'/modules/catalog/images/category_img/');
define('A_CATALOG_IMG_URL','http://'.$_SERVER['SERVER_NAME'].'/modules/catalog/images/category_img/');
define('A_CATALOG_SMALL_IMG_W','50');
define('A_CATALOG_SMALL_IMG_H','50');
define('A_CATALOG_MID_IMG_W','170');
define('A_CATALOG_MID_IMG_H','170');
define('A_PRODUCT_IMG_SIZE','500000');
define('A_PRODUCT_IMG_DIR',''.$_SERVER['DOCUMENT_ROOT'].'/modules/catalog/images/product_img/');
define('A_CATALOG_PDF_PASS',''.$_SERVER['DOCUMENT_ROOT'].'/pdf_docs/');
define('A_CATALOG_PDF_URL','http://'.$_SERVER['SERVER_NAME'].'/pdf_docs/');
define('DEF_TITLE','Термоэлектрические модули');
define('DEF_DESC','Интернет-магазин по продаже термоэлектрических модулей Компании Криотерм');
define('DEF_KEYW','Термоэлектрические модули, Купить, элементы Пельтье, охлаждающий, модуль, Криотерм, ТЭМ элемент, ТЭМ, Каталог ТЭМ, Термоэлектричество, где купить,');
define('MODULE_INSTALL_DIR',''.$_SERVER['DOCUMENT_ROOT'].'/c0ntr0lz0ne/mods/');
define('URL','http://'.$_SERVER['SERVER_NAME'].'/');
define('PATH',''.$_SERVER['DOCUMENT_ROOT'].'/');
define('TBL_PREF','');
define('MODULE_FILE_TYPE','.zip');
//define('SHOP_EMAIL','info@kryotherm.ru');
//define('MAIL_INFO','info@kryotherm.ru');
define('SHOP_EMAIL','bullwinkle321@me.com');
define('SHOP_NAME',' KRYOTHERM');
define('MAIL_INFO','bullwinkle321@me.com');
define('A_PAGE_ICON_SIZE','500000');
define('A_PAGE_ICON_URL','http://'.$_SERVER['SERVER_NAME'].'/images/page_icons/');
define('A_PAGE_ICON_DIR',''.$_SERVER['DOCUMENT_ROOT'].'/images/page_icons/');
?>